import pack.Cashflow;
import pack.TypedCashflow;
import pack.Account;
import pack.AllocatedCashflow;



//rule "Rule 03"
//    when
//         $number : Number( )
//        not  Number( intValue < $number.intValue )
//    then
//        System.out.println("Number found with value: " + $number.intValue() );
//        retract( $number );
//end

//rule "Rule 04"
//    when
//        $cashflow : Cashflow( $date : date, $amount : amount )
//        not Cashflow( date < $date)
//    then
//        System.out.println("Cashflow: "+$date+" :: "+$amount);
//        retract($cashflow);
//end

//rule "Rule 05"
//    when
//        $cashflow : TypedCashflow( $date : date,
//                                   $amount : amount,
//                                   type == TypedCashflow.CREDIT )
//        not TypedCashflow( date < $date,
//                           type == TypedCashflow.CREDIT )
//    then
//        System.out.println($cashflow.toString());
//        retract($cashflow);
//end

rule "Rule 06 - Credit"
    when
        $cashflow : AllocatedCashflow( $account : account,
                                       $date : date,
                                       $amount : amount,
                                       type == TypedCashflow.CREDIT )
        not AllocatedCashflow( account == $account, date < $date)
    then
        System.out.println("Credit: " + $date + " :: " + $amount);
        $account.setBalance($account.getBalance()+$amount);
        System.out.println("Account: " + $account.getAccountNo() +
                           " - new balance: " + $account.getBalance());
        retract($cashflow);
end

rule "Rule 06 - Debit"
    when
        $cashflow : AllocatedCashflow( $account : account,
                            $date : date,
                            $amount : amount,
                            type == TypedCashflow.DEBIT )
        not AllocatedCashflow( account == $account, date < $date)
    then
        System.out.println("Debit: " + $date + " :: " + $amount);
        $account.setBalance($account.getBalance() - $amount);
        System.out.println("Account: " + $account.getAccountNo() +
                           " - new balance: " + $account.getBalance());
        retract($cashflow);
end