import pack.State;


rule Bootstrap
    when
        a : State(name == "A", state == State.NOTRUN )
    then
        System.out.println(a.getName() + " finished" );
        a.setState( State.FINISHED );
end

rule "A to B"
    when
        State(name == "A", state == State.FINISHED )
//        b : State(name == "B", state == State.NOTRUN )
    then
        System.out.println("ok");
//        System.out.println(b.getName() + " finished" );
//        b.setState( State.FINISHED );
end